### ISSUE TITLE
Allow for local creation of Markers

### ISSUE THREAD

**Issue by EinfachJul** [FatLurch/Turret_Enhanced#18]
There should be an option to allow markers to be created only locally, to prevent spam for users that do not need the markers.

**Comment by FatLurch** [comment]
I had looked into being able to change the "channel" for markers in the past and didn't have any luck. I can look into this, though. Thanks!

**Comment by FatLurch** [comment]
This is now incorporated. 

BIS added the ability to place markers in specific channels in version 2.01 - hat tip to them!
