### ISSUE TITLE
addons/turret_enhanced.pbo appears to not be signed after update

### ISSUE THREAD

**Issue by stavae** [FatLurch/Turret_Enhanced#22]
### Issue

After yesterdays update our dedicated Linux server is complaining that `addons\turret_enhanced.pbo` is not signed anymore.
> arma-server    | 15:29:43 Files F:\Steam\steamapps\common\Arma 3\!Workshop\@Turret Enhanced\addons\turret_enhanced.pbo are not signed by a key accepted by this server. To play on this server, remove listed files or install additional accepted keys.

-> Is it possible that you forgot to update it before releasing?

### Proof server/client have same data
Linux server:
``` bash
0(boxxy)(arma-config)/$
find workshop/1623498241/ -type f | xargs sha1sum  | sort
3ba75ab5bd49b5b03c3e9760431af7c3e3157a45  workshop/1623498241/meta.cpp
584839f25b736ac0c154957c026765e8dfdfd1c4  workshop/1623498241/Addons/Turret_Enhanced.pbo.Fat_Lurch_TurretEnhanced.bisign
8f310e610ddf7b0dc0decfba7c34f0e0dbb44e96  workshop/1623498241/keys/Fat_Lurch_TurretEnhanced.bikey
ac58512deda15b69efd7deddf4df7bf38508a7a8  workshop/1623498241/Addons/Turret_Enhanced.pbo
```

Windows client:
``` bash
0(Pc)(/mnt/f/Steam/steamapps/workshop/content/107410)/$
find 1623498241/ -type f | xargs sha1sum | sort
3ba75ab5bd49b5b03c3e9760431af7c3e3157a45  1623498241/meta.cpp
584839f25b736ac0c154957c026765e8dfdfd1c4  1623498241/Addons/Turret_Enhanced.pbo.Fat_Lurch_TurretEnhanced.bisign
8f310e610ddf7b0dc0decfba7c34f0e0dbb44e96  1623498241/keys/Fat_Lurch_TurretEnhanced.bikey
ac58512deda15b69efd7deddf4df7bf38508a7a8  1623498241/Addons/Turret_Enhanced.pbo
```

### Setup info
Our dedicated server runs on a linux (ubuntu) machine within docker and currently run ~40 mods.

The `.bikey` is  is in the `keys/` folder (as a symlink like all the other mods/before the update).
``` bash
steam@29c6c69bb48a:~/arma/keys$ ls -hal Fat_Lurch_TurretEnhanced.bikey
lrwxrwxrwx 1 steam steam 97 Mar 15 15:21 Fat_Lurch_TurretEnhanced.bikey -> /home/steam/arma/steamapps/workshop/content/107410/1623498241/keys/Fat_Lurch_TurretEnhanced.bikey
```

When starting the arma server it `Turret Enhanced` does also show up correctly in the `list of mods`.

**Comment by FatLurch** [comment]
Yes sir, I re-upload a version this morning with an updated key. Thanks!
